"""Add PontoDeColeta table

Revision ID: 5c220746ac3f
Revises: c86f5a70f37f
Create Date: 2025-02-10 02:23:43.227102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c220746ac3f'
down_revision = 'c86f5a70f37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not op.get_bind().engine.dialect.has_table(op.get_bind(), 'pontos_de_coleta'):
        op.create_table('pontos_de_coleta',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('nome', sa.String(length=255), nullable=False),
        sa.Column('endereco', sa.String(length=255), nullable=False),
        sa.Column('bairro', sa.String(length=100), nullable=False),
        sa.Column('cidade', sa.String(length=100), nullable=False),
        sa.Column('estado', sa.String(length=2), nullable=False),
        sa.Column('cep', sa.String(length=10), nullable=True),
        sa.Column('tipos_de_residuos', sa.Text(), nullable=False),
        sa.Column('data_cadastro', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pontos_de_coleta')
    # ### end Alembic commands ###
